@extends('layouts.landing-page')
@section('content')
<div class="main-container">
  <section class="bg-dark text-light height-80">
    <img alt="Image" src="/assets/images/GraficoLight2.jpg" class="bg-image opacity-60" />
    <div class="container">
      <div class="row justify-content-center text-center">
        <div class="col-12 col-md-10 col-lg-7">
          <span class="title-decorative">big data applied to investments</span>
          <h1 class="display-4">Investment in India</h1>
          <span class="lead">A guide to understand the investment of long-term stock value. Investment opportunities in the country with the greatest potential for sustained economic growth over the next ten years</span>
        </div>
        <!--end of col-->
      </div>
      <!--end of row-->
    </div>
    <!--end of container-->
  </section>
  <!--end of section-->

  <!--end of section-->
  <section>
    <article class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-md-8 col-lg-6">
          <blockquote class="blockquote">
            <p class="h4">
              “We specialize in economic analysis, compare companies in the industry and evaluate the fundamentals of the company by projecting based on real numbers and sustainable growth rates.”
            </p>
            <footer class="blockquote-footer title-decorative">
              Patricio Nally, CEO & Financial Analyst
            </footer>
          </blockquote>
          <p class="lead">
            Value investment is an investment strategy that consists in choosing shares of companies that seem to be traded for less than their intrinsic or accounting value. Value investors actively discover actions that they believe the stock market is underestimating. They believe that the market overreacts to good and bad news, resulting in movements in the price of shares that do not correspond to the long-term fundamentals of a company. The mass and exaggerated reaction due to factors external to the company makes it possible to detect the opportunity to obtain profits when buying shares at reduced prices.
          </p>
          <p class="lead">
            Warren Buffett is probably the most well-known value investor today, but there are many others, including Benjamin Graham (Buffet teacher and mentor), Charlie Munger, Christopher Browne (another Graham student) and the hedge fund manager, Seth Klarman.
            <abbr title="Hyper Text Markup Language"></abbr>
          </p>
        </div>
        <!--end of col-->
        <figure class="figure text-center col-12 col-md-10 col-lg-8">
          <img alt="Image" class="img-fluid figure-img rounded" src="/assets/images/BigDataIndia.jpg" />
        </figure>
        <!--end of col-->
        <div class="col-12 col-md-8 col-lg-6">
          <p class="lead">
            The investment of value is the process of doing a detailed and exhaustive analysis work following economic and financial foundations to find these secret sales of shares and buy them at a discount compared to how the market values them. By keeping these companies in the long term, investors can obtain capital gains, by raising the price of these shares for external reasons of the industry or for a positive performance of the company's operational evolution.
          </p>
          <p class="lead">
            In the stock market, the equivalent of a stock that is cheap or discounted is when its shares are undervalued. Value investors expect to benefit from the actions they perceive have a great discount. Investors use various metrics through the use of financial analysis, such as the study of financial performance, income, earnings, operating cash flow and earnings of a company, as well as fundamental factors, such as brand, business model, the target market and the competitive advantage of the company. Some metrics used to value the actions of a company include: Book price (P / B) or book value or, which measures the value of a company's assets and compares them with the price of the shares. If the price is lower than the value of the assets, the shares are undervalued, assuming the company is not in financial difficulties. Free cash flow, which is the cash generated by the income or operations of a company after subtracting costs from expenses. Free cash flow is the remaining cash after expenses have been paid, including operating expenses and large purchases called capital expenditures, which is the purchase of assets such as equipment or the improvement of a manufacturing plant. If a company is generating free cash flow, it will have money left to invest in the future of the business, pay debts, pay dividends or rewards to shareholders and issue share repurchases. Price to earnings (P / E), which shows the company's earnings history to determine if the share price does not reflect all earnings or is undervalued.
          </p>
          <p class="lead">
            Of course, there are many other metrics used in the analysis, including the analysis of debt, equity, sales and revenue growth. After reviewing these metrics, the value investor may decide to buy shares if the comparative value (the current price of the share with respect to the intrinsic value of his company) is attractive enough, or offers possibilities of rising.
          </p>
          <p class="lead">
            Let's talk about the safety margin, a relevant concept in the world of investments. The safety margin principle, one of the keys to a successful value investment, is based on the fact that buying shares at bargain prices gives you a better chance of earning profits later when you sell them (when the market price goes up). The safety margin also makes you less likely to lose money if the action does not work as expected, reducing the risk.
          </p>
          <p class="h4" style="text-align:center">
            Value Investment Strategies
          </p>
          <p class="lead">
            The key to buying an undervalued stock is to thoroughly investigate the company and make common sense decisions. Value investor Christopher H. Browne recommends asking if a company is likely to increase its revenue through the following methods: Increase product prices. Increase in sales figures Decreasing expenses Sell ​​or close unprofitable divisions Browne also suggests studying the competitors of a company to assess its prospects for future growth. Bottom line: there are still no quantitative software programs available to help achieve these answers, which makes investing in securities a great guessing game. But the answers to all these questions tend to be speculative, without real numerical supporting data. For this reason, Warren Buffett recommends investing only in industries where he has worked personally or whose consumer goods he knows, such as cars, clothing, appliances and food. One thing that investors can do is choose the shares of companies that sell high demand products and services. While it is difficult to predict when new innovative products will capture market share, it is easy to measure how long a company has been in the business and study how it has adapted to the challenges over time.
          </p>
          <p class="h4" style="text-align:center">
            What is diversifying investment risk?
          </p>
          <p class="lead">
            It consists of distributing the money that a person or organization wants to invest in different assets with the objective of minimizing the risk they have, different assets with different risk, profitability, liquidity and from various industries. In this way, we expand the options we have to invest our money and we are less likely to lose all our money.
          </p>
          <p class="lead">
            The diversification approach is logical to reduce risk when investing. If we bet all our money on a card we have two options: win or lose. If it goes well we can get great benefits. However, in case of a cross, we can lose some of our capital. Diversification is the key to successful investments and analysis of Mcnally Finance India, also offering the analysis of solid global markets and emerging markets with greater risk and return.
          </p>
          <p class="h4" style="text-align:center">
            Mcnally's team covers more than 4,380 listed companies in India, with robust forecasts and evaluations of past performance and future estimates of all their financial metrics, emphasizing fundamental data. All in real time through the Mcnally financial platform.
          </p>
          <div class="row justify-content-center text-center section-outro">
              <div class="col-lg-4 col-md-5">
                <h6>Did we miss something?</h6>
                <p>Feel free to drop us a line with any fruther questions. One of our support team will get back to you ASAP.</p>
                <a href="mailto:contact@mcnally.in">Get in touch &rsaquo;</a>
              </div>
              <!--end of col-->
            </div>
            <!--end of row-->
        <!--end of col-->
      </div>
      <!--end of row-->
    </article>
    <!--end of container-->
  </section>
  <!--end of section-->
      
  <section class="bg-white">
    <div class="container">
      <div class="row section-intro">
        <div class="col text-center">
          <h3 class="h1">Do not wait, register now with a 20% off in the first month.</h3>
        </div>
        <!--end of col-->
      </div>
      <!--end of row-->
      <form>
          <div class="row">
            <div class="col-12 col-sm-6 col-lg-3">
              <div class="form-group">
                <label for="username">Firstname</label>
                <input id="username" type="text" class="form-control form-control-lg" placeholder="Firstname">
              </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-3">
              <div class="form-group">
                <label for="email">Lastname</label>
                <input id="email" type="text" class="form-control form-control-lg" placeholder="Lastname">
              </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-3">
              <div class="form-group">
                <label for="password">Email Address</label>
                <input id="password" type="email" class="form-control form-control-lg" placeholder="you@domain.com">
              </div>
            </div>
            <div class="col-12 col-sm-6 col-lg-3">
              <div class="form-group">
                <label for="button">&nbsp;</label>
                <button id="button" type="submit" class="btn btn-lg btn-block btn-success">Sign up for Mcnally</button>
              </div>
            </div>
          </div>
          <!--end of row-->
        </form>
    </div>
    <!--end of container-->
  </section>
</div>
@endsection
